### ISSUE TITLE
编译不通过,python小白求教

### ISSUE THREAD

**Issue by whitefcy** [zyHan2077/EpeAutoReserve#1]
![image](https://user-images.githubusercontent.com/89247461/156185033-d410bdb6-ce04-492a-ae60-289c001c5e41.png)

**Comment by zyHan2077** [comment]
你可以在上一行加一个print(r3.json())，看看是不是没有正确读到网页

**Comment by whitefcy** [comment]
> 你可以在上一行加一个print(r3.json())，看看是不是没有正确读到网页

报了相同的错

**Comment by zyHan2077** [comment]
就，print打印的结果是什么

**Comment by whitefcy** [comment]
![image](https://user-images.githubusercontent.com/89247461/156272386-95ab60f1-1647-473e-ae67-d939744f67f8.png)
应该是这个

**Comment by whitefcy** [comment]
已经把S改成字符串了

**Comment by zyHan2077** [comment]
就是S没改对，不会弄的话，可以留微信找我拿正确的S

**Comment by whitefcy** [comment]
微信号是whitefcy，麻烦了

**Comment by zhurboo** [comment]
订场太卷了，求个S！

**Comment by zhurboo** [comment]
⑤4零9幺幺9⑦9，感谢！
