### ISSUE TITLE
Magic number S求教

### ISSUE THREAD

**Issue by BUAAthreebodies** [zyHan2077/EpeAutoReserve#2]
大佬，我想把你的程序换成北航自动预约，可是S的值不知道，方便告诉吗？或者得到S的方式也行，不知道两个学校的是不是一样的

**Comment by zyHan2077** [comment]
没啥好办法，用浏览器阅读网站源码，找到验证的部分，有一些代码是生成这个S的，启用javascript单步调试应当可以读出这个值
